---
title: "index"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Summary Code

For each piece of Summary Info(1 x 5): Include the piece of information using in-line R code in the paragraph

## Aggregate Table

Introduces the table, explaining why the particular grouping calculation was performed
Displays well formatted column names
Successfully renders the table in the report using an appropriate package (e.g., don't just print
out the data frame)
Interprets information the table, honing in on important information
 
## Chart Number 1
description of what the chart attempts to answer/understand
Interprets information from the chart, honing in on important information

## Chart Number 2
description of what the chart attempts to answer/understand
Interprets information from the chart, honing in on important information

## Chart Number 3
description of what the chart attempts to answer/understand
Interprets information from the chart, honing in on important information
 